### PR TITLE
Update 2.0.31

### PR DESCRIPTION
**Pull request by manics**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

conmon 2.0.30+ requires seccomp.

### CODE REVIEW

**Comment by manics** [comment]
@conda-forge-admin, please rerender

**Comment by dhirschfeld** [comment]
Thanks for picking this up @manics! It would be great to have the latest `podman` available via conda so I'm keen to see this merged.

I know @mbargull is busy, but hopefully he has time to review this. In any case, it might be an idea to [open an issue](https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-add-user-username) to get yourself access and hence double the [bus-factor](https://en.wikipedia.org/wiki/Bus_factor) for this feedstock.

**Comment by manics** [comment]
@dhirschfeld I've added myself to the recipe-maintainers in this PR. Do you want me to add you too? I don't have any special expertise in building Podman, only in using it, and like you I'm keen to see it in conda-forge.

**Comment by dhirschfeld** [comment]
> *I don't have any special expertise in building Podman*

I'm in a similar situation but happy for you to add me here also, to help out as I can...

**Comment by dhirschfeld** [comment]
> *I don't have any special expertise in building Podman*

I'm in a similar situation but happy for you to add me here also, to help out as I can...

**Comment by dhirschfeld** [comment]
ping @mbargull, @conda-forge/conmon!

**Comment by bollwyvl** [comment]
Perhaps @conda-forge/core would take a look at this? it looks like two active maintainers would be added.

**Comment by bollwyvl** [comment]
thanks @dopplershift !

**Comment by dhirschfeld** [comment]
Thanks @dopplershift, and thanks @bollwyvl for pinging core - it was on my TODO list!

**Comment by manics** [comment]
Thanks for sorting this out!

**Pull request merged**
